name: gitee-sync # yml文件名

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  gitee: # 任务名
    runs-on: ubuntu-latest
    environment: production
    steps:
     - uses: wearerequired/git-mirror-action@master #开源actions包
       env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
       with:
          source-repo: "git@github.com:liyao1520/lol-assets.git" # github仓库地址
          destination-repo: "git@gitee.com:lol-assets/lol-assets.git" # gitee仓库地址
