name: autoUpload # yml文件名

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run-autoUpload: # 任务名
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: lol-assets/lol-assets
          username: lol-assets
          password: ${{ secrets.GITEE_PASSWORD }}
