name: test # yml文件名

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-test: # 任务名
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main #采用main分支下的
      - name: Setup Node.js
        uses: actions/setup-node@v2 #安装node.js
        with:
          node-version: "18"

      - name: Install Dependency
        run: |
          npm install
      - name: npm run test
        run: |
          touch .env
          echo TENCENTCLOUD_SECRET_ID=${{ secrets.TENCENTCLOUD_SECRET_ID }} >> .env
          echo TENCENTCLOUD_SECRET_KEY=${{ secrets.TENCENTCLOUD_SECRET_KEY }} >> .env
          npm run test  # 要运行的js脚本，放在根目录下
